import type { User, Post, Dispute } from '@/lib/types';

export const mockUsers: Record<string, User> = {
  user1: {
    id: 'user1',
    name: 'Alex Doe',
    username: 'alexdoe',
    avatarUrl: 'https://placehold.co/100x100.png',
    'data-ai-hint': 'man portrait',
    trustScore: 85,
    isVerified: true,
    bio: 'Digital craftsman, coffee enthusiast, and advocate for clarity on the web.',
  },
  user2: {
    id: 'user2',
    name: 'Jane Smith',
    username: 'janesmith',
    avatarUrl: 'https://placehold.co/100x100.png',
    'data-ai-hint': 'woman portrait',
    trustScore: 92,
    isVerified: true,
    bio: 'Building beautiful and accessible user experiences. Cat lover. Tea drinker.',
  },
  user3: {
    id: 'user3',
    name: 'Samuel Green',
    username: 'samgreen',
    avatarUrl: 'https://placehold.co/100x100.png',
    'data-ai-hint': 'person smiling',
    trustScore: 78,
    isVerified: false,
    bio: 'Exploring the intersection of technology and society. All opinions are my own.',
  },
  user4: {
    id: 'user4',
    name: 'Shame Official',
    username: 'shame',
    avatarUrl: 'https://placehold.co/100x100.png',
    'data-ai-hint': 'shield logo',
    trustScore: 100,
    isVerified: true,
    bio: 'The official account for the Shame platform. Promoting transparency and accountability.',
  },
};

export const mockPosts: Post[] = [
  {
    id: 'post1',
    type: 'endorsement',
    author: mockUsers.user2,
    postingAs: 'verified',
    entity: 'The Local Cafe',
    text: "Just had the best customer service experience at The Local Cafe. The staff was incredibly friendly and helpful. Highly recommend their cortado!",
    category: 'Customer Service',
    createdAt: '2h',
    commentsCount: 12,
    upvotes: 45,
    downvotes: 2,
    reposts: 5,
    bookmarks: 3,
    sentiment: {
      score: 0.9,
      biasDetected: false,
    },
    summary: "A glowing review of The Local Cafe's customer service and coffee.",
  },
  {
    id: 'post2',
    type: 'report',
    author: mockUsers.user3,
    postingAs: 'whistleblower',
    entity: 'Speedy Shippers',
    text: "My package from 'Speedy Shippers' arrived two weeks late and the box was damaged. Their tracking system was also down for the entire duration. Very frustrating experience.",
    mediaUrl: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'damaged package',
    mediaType: 'image',
    category: 'Logistics',
    createdAt: '5h',
    commentsCount: 34,
    upvotes: 8,
    downvotes: 29,
    reposts: 2,
    bookmarks: 1,
    sentiment: {
      score: -0.8,
      biasDetected: false,
    },
  },
  {
    id: 'post5',
    type: 'post',
    author: mockUsers.user1,
    postingAs: 'verified',
    text: "Just enjoying a beautiful day at the park. Sometimes it's the simple things in life that matter most.",
    mediaUrl: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'park nature',
    mediaType: 'image',
    createdAt: '8h',
    commentsCount: 15,
    upvotes: 102,
    downvotes: 4,
    reposts: 8,
    bookmarks: 12,
  },
  {
    id: 'post3',
    type: 'endorsement',
    author: mockUsers.user1,
    postingAs: 'verified',
    entity: 'Productivity Pro App',
    text: "I want to give a shoutout to the developers of the 'Productivity Pro' app. The new update is fantastic, and it has genuinely improved my workflow. The UI is clean and intuitive.",
    category: 'Technology',
    createdAt: '1d',
    commentsCount: 5,
    upvotes: 78,
    downvotes: 1,
    reposts: 12,
    bookmarks: 9,
    sentiment: {
      score: 0.95,
      biasDetected: false,
    },
    summary: 'Positive feedback on the new update for the "Productivity Pro" app.'
  },
  {
    id: 'post4',
    type: 'report',
    author: mockUsers.user2,
    postingAs: 'anonymous',
    entity: 'Innovate Inc.',
    text: 'Attended a workshop by "Innovate Inc." and the content was completely outdated. The speaker seemed unprepared and couldn\'t answer basic questions. Not worth the price of admission.',
    category: 'Education',
    createdAt: '2d',
    commentsCount: 21,
    upvotes: 15,
    downvotes: 4,
    reposts: 1,
    bookmarks: 0,
    sentiment: {
      score: -0.7,
      biasDetected: true,
      biasExplanation: 'The language used is strong and subjective, which may indicate a personal bias against the company or speaker.'
    }
  },
  {
    id: 'post6',
    type: 'endorsement',
    author: mockUsers.user3,
    postingAs: 'verified',
    entity: 'Alex Doe', // Target user1 by name
    text: 'Had a great collaboration with Alex on a recent project. A true professional with a keen eye for detail. Highly recommended!',
    category: 'Professionalism',
    createdAt: '3d',
    commentsCount: 8,
    upvotes: 62,
    downvotes: 0,
    reposts: 4,
    bookmarks: 2,
    sentiment: {
      score: 0.98,
      biasDetected: false,
    },
    summary:
      'A strong professional endorsement for Alex Doe, highlighting collaboration and attention to detail.',
  },
];

export const mockDisputes: Dispute[] = [
  {
    id: 'dispute1',
    title: 'Dispute over "Speedy Shippers" report accuracy',
    description: 'The company "Speedy Shippers" is disputing the report made by @samgreen, claiming the delivery was delayed due to weather conditions not mentioned in the report. They have provided shipping logs as evidence.',
    involvedParties: [mockUsers.user3, mockUsers.user4],
    createdAt: '1d',
    status: 'voting',
    commentsCount: 56,
    poll: {
      question: 'Whose account do you find more credible?',
      options: [
        { text: '@samgreen\'s report', votes: 102 },
        { text: 'Speedy Shipper\'s rebuttal', votes: 45 },
        { text: 'Need more information', votes: 33 },
      ],
    },
    verdict: null,
  },
  {
    id: 'dispute2',
    title: 'Community review of "Innovate Inc." workshop report',
    description: 'The report against "Innovate Inc." by @janesmith has been flagged for potential bias. The Village Square is now open for community discussion and polling to determine the fairness of the initial report.',
    involvedParties: [mockUsers.user2, mockUsers.user4],
    createdAt: '3d',
    status: 'closed',
    commentsCount: 123,
    poll: {
      question: 'Is the report on "Innovate Inc." fair and unbiased?',
      options: [
        { text: 'Yes, it is fair', votes: 88 },
        { text: 'No, it shows significant bias', votes: 154 },
      ],
    },
    verdict: {
      moderator: mockUsers.user4,
      decision: 'The original report by @janesmith will be marked with a "Community Disputed" tag.',
      reason: 'Based on the community poll and discussion, the majority found the report to contain strong subjective language that could indicate bias. While the negative experience is valid, the post will be flagged to encourage readers to view comments for a balanced perspective.',
    },
  },
];
